server:
  port: 8090

spring:
  datasource:
    url:
      jdbc:
        h2:
          mem: testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type:
          descriptor:
            sql: trace
        ddl-auto: create-drop
  h2:
    console:
      enabled: true
